//! Every registered `bearcad.*` function, with the arguments it takes (#1664).
//!
//! The published API page used to give call shapes for 72 of 262 names and list the rest as
//! bare bullets, so an agent that read it could not call two thirds of the API. This table
//! is the other half of that page: one line per function, generated once from the option
//! keys each call validates and kept honest by
//! [`super::api::tests::every_registered_function_has_a_signature`] — a new function fails
//! the test until it is listed here.
//!
//! `{ … }` is a single options table; `?` marks an optional argument or key. Where a call
//! takes more than the shape shows (an element table, a face spec), the prose sections of
//! the guide carry the detail.

/// Full name → the call's shape, sorted by name.
pub const SIGNATURES: &[(&str, &str)] = &[
    ("bearcad.add_parameter"               , "bearcad.add_parameter(name, expression)"),
    ("bearcad.add_unit_instance"           , "bearcad.add_unit_instance{ unit, name }"),
    ("bearcad.ui.begin_combine"               , "bearcad.ui.begin_combine{ op, a, b, keep_b }"),
    ("bearcad.ui.begin_edit_section_plane"    , "bearcad.ui.begin_edit_section_plane{ view, cut }"),
    ("bearcad.ui.begin_joint"                 , "bearcad.ui.begin_joint{ index, a, b, parts, kind, lead, base, face, line_up, frame_origin, frame_axis, frame_axis2, position, position2, position3, slide_min, slide_max, slide_min_to, slide_max_to, turn_min, turn_max, name }   -- face = { moving, fixed, flip?, offset?, spin? }"),
    ("bearcad.ui.begin_move"                  , "bearcad.ui.begin_move{ bodies, images, x, y, z, rotate, rx, ry, rz, roll, flip, spin, gap, from, to }   -- from/to are mate-point lists; rotate = { x, y, z }"),
    ("bearcad.bake"                        , "bearcad.bake(index)   -- freeze a boolean's result into standalone bodies and consume its inputs"),
    ("bearcad.begin_sketch"                , "bearcad.begin_sketch(…)"),
    ("bearcad.body_cylinders"              , "bearcad.body_cylinders(index)"),
    ("bearcad.extrude_edges"               , "bearcad.extrude_edges(index)   -- edge refs fillet_edge/chamfer_edge accept: kind vertical|top|bottom"),
    ("bearcad.body_edges"                  , "bearcad.body_edges(index)"),
    ("bearcad.body_faces"                  , "bearcad.body_faces(index)"),
    ("bearcad.body_stats"                  , "bearcad.body_stats(index)"),
    ("bearcad.calibrate_image"             , "bearcad.calibrate_image{ image, from, to, length }"),
    ("bearcad.calibration_point"           , "bearcad.calibration_point{ image, index, x, y }"),
    ("bearcad.chamfer"                     , "bearcad.chamfer{ body, edges, edge, extrusion, shape, primitive, distance }"),
    ("bearcad.chamfer_edge"                , "bearcad.chamfer_edge{ body, edges, edge, extrusion, shape, primitive, distance }"),
    ("bearcad.chamfer_vertex"              , "bearcad.chamfer_vertex{ points, point, distance }"),
    ("bearcad.circle"                      , "bearcad.circle{ x, y, r, radius, diameter, name }"),
    ("bearcad.clear"                       , "bearcad.clear()"),
    ("bearcad.clear_selection"             , "bearcad.clear_selection()"),
    ("bearcad.clone_unit_instance"         , "bearcad.clone_unit_instance{ instance }"),
    ("bearcad.combine"                     , "bearcad.combine{ op, a, b, keep_b, name }"),
    ("bearcad.ui.commit_dim"                  , "bearcad.ui.commit_dim()"),
    ("bearcad.ui.commit_plane"                , "bearcad.ui.commit_plane()"),
    ("bearcad.component"                   , "bearcad.component{ name, parent }?"),
    ("bearcad.constrain"                   , "bearcad.constrain(kind, a, b, …)"),
    ("bearcad.ui.constraint_shortcut"         , "bearcad.ui.constraint_shortcut(key)"),
    ("bearcad.copy"                        , "bearcad.copy()"),
    ("bearcad.count"                       , "bearcad.count(kind)"),
    ("bearcad.count_saved"                 , "bearcad.count_saved(kind)"),
    ("bearcad.cross_section"               , "bearcad.cross_section{ name }"),
    ("bearcad.box"                         , "bearcad.box{ width, depth, height, at?, normal?, u_axis?, name? }"),
    ("bearcad.cube"                        , "bearcad.cube{ size, width, depth, height, at?, normal?, u_axis?, name? }"),
    ("bearcad.cuboid"                      , "bearcad.cuboid{ width, depth, height, at?, normal?, u_axis?, name? }"),
    ("bearcad.cylinder"                    , "bearcad.cylinder{ radius, height, at?, normal?, u_axis?, name? }"),
    ("bearcad.delete"                      , "bearcad.delete(element_or_list)"),
    ("bearcad.delete_parameter"            , "bearcad.delete_parameter(name)"),
    ("bearcad.delete_selection"            , "bearcad.delete_selection()"),
    ("bearcad.derive_parameter"            , "bearcad.derive_parameter{ kind, a, b, body, body_b, name, instance, face, edge }"),
    ("bearcad.dimension"                   , "bearcad.dimension{ kind, value, index, a, b, sign, point, line, anchor, mover }"),
    ("bearcad.ui.drag_gizmo"                  , "bearcad.ui.drag_gizmo{ name, by }"),
    ("bearcad.drag_line"                   , "bearcad.drag_line({ … }, anchor_u?, anchor_v?, u?, v?)"),
    ("bearcad.drag_vertex"                 , "bearcad.drag_vertex({ … }, u?, v?)"),
    ("bearcad.drawing"                     , "bearcad.drawing{ name }?"),
    ("bearcad.drawing_align_view"          , "bearcad.drawing_align_view{ drawing, parent, dir, pos }"),
    ("bearcad.drawing_angle"               , "bearcad.drawing_angle{ drawing, view, edge1, edge2 }"),
    ("bearcad.drawing_circle_dim_offset"   , "bearcad.drawing_circle_dim_offset{ drawing, view, center, offset }"),
    ("bearcad.drawing_circle_dimension"    , "bearcad.drawing_circle_dimension{ drawing, view, center }"),
    ("bearcad.drawing_curve_dimension"     , "bearcad.drawing_curve_dimension{ drawing, view, points }"),
    ("bearcad.drawing_dim_offset"          , "bearcad.drawing_dim_offset{ drawing, view, offset, a, b }"),
    ("bearcad.drawing_dimension"           , "bearcad.drawing_dimension{ drawing, view, a, b }"),
    ("bearcad.drawing_move_view"           , "bearcad.drawing_move_view{ drawing, view, x, y }"),
    ("bearcad.drawing_page"                , "bearcad.drawing_page{ drawing, width, height, margin }"),
    ("bearcad.drawing_point_dimension"     , "bearcad.drawing_point_dimension{ drawing, view, a, b, axis }"),
    ("bearcad.drawing_loupe"               , "bearcad.drawing_loupe{ drawing, view, at, radius, to, to_radius }   -- at/to are {u, v} in the view's projected mm"),
    ("bearcad.edit_drawing_loupe"          , "bearcad.edit_drawing_loupe{ drawing, view, index, at?, radius?, to?, to_radius?, style? }   -- style is a drawing view style, or \"view\" to follow the projection's"),
    ("bearcad.drawing_loupe_dimension"     , "bearcad.drawing_loupe_dimension{ drawing, view, index, a, b }   -- show/hide one edge's length dimension on a loupe; a/b are its world endpoints"),
    ("bearcad.delete_drawing_loupe"        , "bearcad.delete_drawing_loupe{ drawing, view, index }"),
    ("bearcad.drawing_loupes"              , "bearcad.drawing_loupes{ drawing, view }   -- { at, radius, to, to_radius, zoom, style, dimensions } each"),
    ("bearcad.drawing_point_dimension_axis" , "bearcad.drawing_point_dimension_axis{ drawing, view, index, axis }"),
    ("bearcad.drawing_point_dim_offset"    , "bearcad.drawing_point_dim_offset{ drawing, view, index, offset }"),
    ("bearcad.drawing_text"                , "bearcad.drawing_text{ drawing, text, x, y, wrap? }   -- x/y are page fractions (0–1)"),
    ("bearcad.drawing_view"                , "bearcad.drawing_view{ drawing, body, bodies, component, sketch, cross_section, orientation }"),
    ("bearcad.drawing_view_section"        , "bearcad.drawing_view_section{ drawing, view, cross_section }"),
    ("bearcad.drawing_view_add"            , "bearcad.drawing_view_add{ drawing, view, body, bodies, component }"),
    ("bearcad.drawing_view_align_lines"    , "bearcad.drawing_view_align_lines{ drawing, view, show }"),
    ("bearcad.drawing_view_label"          , "bearcad.drawing_view_label{ drawing, view, hidden, pos, text }"),
    ("bearcad.drawing_view_lines"          , "bearcad.drawing_view_lines{ drawing, view }          -- the lines the view draws: { x1, y1, x2, y2 } in view mm, hidden lines already removed"),
    ("bearcad.drawing_view_orientation"    , "bearcad.drawing_view_orientation{ drawing, view, orientation }"),
    ("bearcad.drawing_view_size"           , "bearcad.drawing_view_size{ drawing, view, width, height, size_x, size_y }"),
    ("bearcad.drawing_paper"               , "bearcad.drawing_paper{ drawing, paper }   -- white | dark (the editor's sheet; exports are always white)"),
    ("bearcad.drawing_view_style"          , "bearcad.drawing_view_style{ drawing, view, style }   -- visible, wireframe, shaded, colorful, loose_pencil, color_pencil, watercolor"),
    ("bearcad.drawing_style"               , "bearcad.drawing_style{ drawing, style }              -- the style projections added to this page start in"),
    ("bearcad.drawing_views"               , "bearcad.drawing_views(index)"),
    ("bearcad.edit_chamfer"                , "bearcad.edit_chamfer{ index, edge, edges, body, extrusion, primitive, distance }"),
    ("bearcad.edit_circle"                 , "bearcad.edit_circle{ index, r, radius, diameter, name }"),
    ("bearcad.edit_combine"                , "bearcad.edit_combine{ index, op, a, b, keep_b }"),
    ("bearcad.ui.edit_dim"                    , "bearcad.ui.edit_dim(axis)"),
    ("bearcad.edit_extrusion"              , "bearcad.edit_extrusion{ index, extrusion, distance, by, to }"),
    ("bearcad.edit_fillet"                 , "bearcad.edit_fillet{ index, edge, edges, body, extrusion, primitive, radius }"),
    ("bearcad.edit_joint"                  , "bearcad.edit_joint{ index, a, b, parts, kind, lead, base, face, line_up, frame_origin, frame_axis, frame_axis2, position, position2, position3, slide_min, slide_max, slide_min_to, slide_max_to, turn_min, turn_max, name }   -- face = { moving, fixed, flip?, offset?, spin? }"),
    ("bearcad.edit_loft"                   , "bearcad.edit_loft{ index, circle, circles, polygon, polygons, bodies, body, name }"),
    ("bearcad.edit_mirror"                 , "bearcad.edit_mirror{ index, plane, bodies, output }"),
    ("bearcad.edit_move"                   , "bearcad.edit_move{ index, bodies, images, x, y, z, rotate, rx, ry, rz, roll, flip, spin, gap, from, to }   -- from/to are mate-point lists; rotate = { x, y, z }"),
    ("bearcad.edit_parameter"              , "bearcad.edit_parameter{ name, private, min, max, step, rename }"),
    ("bearcad.ui.edit_plane"                  , "bearcad.ui.edit_plane(index)"),
    ("bearcad.edit_repeat"                 , "bearcad.edit_repeat{ index, bodies, axis, around, flip, mode, count, spacing, length, to }"),
    ("bearcad.edit_revolve"                , "bearcad.edit_revolve{ index, circle, circles, polygon, axis, angle, revolutions, pitch, offset, gap, symmetric, bodies, body, name }"),
    ("bearcad.edit_shape"                  , "bearcad.edit_shape{ index, shape, at, normal, u_axis, width, depth, height, size, radius, name }"),
    ("bearcad.edit_shell"                  , "bearcad.edit_shell{ index, bodies, faces, thickness }"),
    ("bearcad.edit_sketch_mirror"          , "bearcad.edit_sketch_mirror{ index, sketch, line, lines, circles }"),
    ("bearcad.edit_sketch_offset"          , "bearcad.edit_sketch_offset{ index, sketch, lines, circles, distance, construction }"),
    ("bearcad.edit_sketch_repeat"          , "bearcad.edit_sketch_repeat{ index, sketch, lines, circles, angle, dir, mode, count, spacing, length }"),
    ("bearcad.edit_sketch_slice"           , "bearcad.edit_sketch_slice{ index, lines, circles, faces, cutters }"),
    ("bearcad.edit_slice"                  , "bearcad.edit_slice{ index, bodies, cutters, extend }"),
    ("bearcad.edit_sweep"                  , "bearcad.edit_sweep{ index, circle, circles, polygon, path, bodies, body, name }"),
    ("bearcad.id"                          , "bearcad.id(element)   -- the element's stable, never-reused id"),
    ("bearcad.element"                     , "bearcad.element(kind, index)   -- or bearcad.element(id_or_name); the lookup"),
    ("bearcad.exit_sketch"                 , "bearcad.exit_sketch()"),
    ("bearcad.ui.exploder"                    , "bearcad.ui.exploder()"),
    ("bearcad.export_3mf"                  , "bearcad.export_3mf(path, body?)"),
    ("bearcad.export_drawing_pdf"          , "bearcad.export_drawing_pdf{ drawing, path }"),
    ("bearcad.export_drawing_svg"          , "bearcad.export_drawing_svg{ drawing, path }"),
    ("bearcad.export_preview"              , "bearcad.export_preview(path)"),
    ("bearcad.export_step"                 , "bearcad.export_step(path, body?)"),
    ("bearcad.export_stl"                  , "bearcad.export_stl(path, body?)"),
    ("bearcad.extrude"                     , "bearcad.extrude{ distance, to, profiles, circle, circles, polygon, polygons, text, boolean, body, name, symmetric, taper, taper_mode }"),
    ("bearcad.extrude_face"                , "bearcad.extrude_face{ to, distance, body, name }"),
    ("bearcad.fillet"                      , "bearcad.fillet{ body, edges, edge, extrusion, shape, primitive, r, radius, diameter }"),
    ("bearcad.fillet_edge"                 , "bearcad.fillet_edge{ body, edges, edge, extrusion, shape, primitive, r, radius, diameter }"),
    ("bearcad.fillet_vertex"               , "bearcad.fillet_vertex{ points, point, radius }"),
    ("bearcad.find"                        , "bearcad.find(name)   -- sugar for bearcad.element(name); nil if missing"),
    ("bearcad.get"                         , "bearcad.get(handle|{ kind, index }|kind, index)"),
    ("bearcad.ui.gizmo"                       , "bearcad.ui.gizmo(name)"),
    ("bearcad.ui.gizmos"                      , "bearcad.ui.gizmos()"),
    ("bearcad.ui.hovered"                     , "bearcad.ui.hovered()"),
    ("bearcad.image_corners"               , "bearcad.image_corners(index)"),
    ("bearcad.image_opacity"               , "bearcad.image_opacity{ image, opacity }"),
    ("bearcad.globals"                     , "bearcad.globals()"),
    ("bearcad.import_image"                , "bearcad.import_image(\"path\" | { path, plane? })"),
    ("bearcad.import_lua"                  , "bearcad.import_lua(value)"),
    ("bearcad.import_step"                 , "bearcad.import_step(path)"),
    ("bearcad.import_stl"                  , "bearcad.import_stl(path)"),
    ("bearcad.import_unit"                 , "bearcad.import_unit(value)"),
    ("bearcad.joint"                       , "bearcad.joint{ index, a, b, parts, kind, lead, base, face, line_up, frame_origin, frame_axis, frame_axis2, position, position2, position3, slide_min, slide_max, slide_min_to, slide_max_to, turn_min, turn_max, name }   -- face = { moving, fixed, flip?, offset?, spin? }"),
    ("bearcad.line"                        , "bearcad.line{ x, y, x1, y1, length, angle, bezier, dimension, name }"),
    ("bearcad.line_endpoints"              , "bearcad.line_endpoints(index)"),
    ("bearcad.loft"                        , "bearcad.loft{ profiles, circle, circles, polygon, polygons, bodies, body, name }"),
    ("bearcad.material"                    , "bearcad.material{ name, color, bodies }   -- no color + an existing name applies that material"),
    ("bearcad.debug.mesh_cache"            , "bearcad.debug.mesh_cache()"),
    ("bearcad.mirror_bodies"               , "bearcad.mirror_bodies{ plane, bodies, output, name }"),
    ("bearcad.mirror_sketch"               , "bearcad.mirror_sketch{ sketch, line, lines, circles }"),
    ("bearcad.move_bodies"                 , "bearcad.move_bodies{ bodies, images, x, y, z, rotate, rx, ry, rz, roll, flip, spin, gap, from, to, name }   -- from/to are mate-point lists; rotate = { x, y, z }"),
    ("bearcad.ui.move_preview"                , "bearcad.ui.move_preview()"),
    ("bearcad.move_to_component"           , "bearcad.move_to_component{ kind, index, component }"),
    ("bearcad.new"                         , "bearcad.new()"),
    ("bearcad.offset_sketch"               , "bearcad.offset_sketch{ sketch, lines, circles, distance, construction }"),
    ("bearcad.open"                        , "bearcad.open(path)"),
    ("bearcad.open_sketch"                 , "bearcad.open_sketch(sketch)"),
    ("bearcad.parameter_edit"              , "bearcad.parameter_edit(name, field)"),
    ("bearcad.parameter_editing"           , "bearcad.parameter_editing()"),
    ("bearcad.parameter_expression"        , "bearcad.parameter_expression(name)"),
    ("bearcad.parameter_from_line_length"  , "bearcad.parameter_from_line_length(line, name?)"),
    ("bearcad.parameter_options"           , "bearcad.parameter_options(name, open?)"),
    ("bearcad.parameter_slider"            , "bearcad.parameter_slider(name, value?)"),
    ("bearcad.parameter_value"             , "bearcad.parameter_value(name)"),
    ("bearcad.paste"                       , "bearcad.paste{ linked, x, y, z }?"),
    ("bearcad.ui.picker"                      , "bearcad.ui.picker(name)"),
    ("bearcad.ui.pickers"                     , "bearcad.ui.pickers()"),
    ("bearcad.plane"                       , "bearcad.plane{ offset, from, origin, normal, axis, angle, name }"),
    ("bearcad.project"                     , "bearcad.project{ entities, body, bodies, plane, planes, kind, index, name, type }?"),
    ("bearcad.quit"                        , "bearcad.quit()"),
    ("bearcad.rebuild_geometry"            , "bearcad.rebuild_geometry()"),
    ("bearcad.rect"                        , "bearcad.rect{ x, y, width, height, name }"),
    ("bearcad.remove_calibration_point"    , "bearcad.remove_calibration_point{ image, index }"),
    ("bearcad.repeat_bodies"               , "bearcad.repeat_bodies{ bodies, axis, around, flip, mode, count, spacing, length, to, name }"),
    ("bearcad.repeat_cut"                  , "bearcad.repeat_cut{ cuts, axis, around, flip, mode, count, spacing, length, to }"),
    ("bearcad.repeat_sketch"               , "bearcad.repeat_sketch{ sketch, lines, circles, angle, dir, mode, count, spacing, length }"),
    ("bearcad.repeat_sketches"             , "bearcad.repeat_sketches{ sketches, axis, around, flip, mode, count, spacing, length, to }"),
    ("bearcad.revert_joint"                , "bearcad.revert_joint(op)"),
    ("bearcad.revert_joints"               , "bearcad.revert_joints()"),
    ("bearcad.revolve"                     , "bearcad.revolve{ profiles, circle, circles, polygon, axis, symmetric, bodies, body, revolutions, angle, pitch, name }"),
    ("bearcad.save"                        , "bearcad.save(path?)"),
    ("bearcad.section_plane"               , "bearcad.section_plane{ view, plane, origin, normal, offset, roll, depth, flip, bodies, exclude_bodies }   -- depth: how far the cut reaches; omitted or false cuts through"),
    ("bearcad.section_planes"              , "bearcad.section_planes(view?)   -- view: cross-section index or name; omitted = the view being edited"),
    ("bearcad.edit_section_plane"          , "bearcad.edit_section_plane{ view, cut, offset, roll, depth, flip, bodies, exclude_bodies }"),
    ("bearcad.delete_section_plane"        , "bearcad.delete_section_plane{ view, cut }"),
    ("bearcad.section_stats"               , "bearcad.section_stats(index)   -- body as the open cross-section shows it: { volume, triangles, bbox }"),
    ("bearcad.select"                      , "bearcad.select(…)"),
    ("bearcad.selection"                   , "bearcad.selection()"),
    ("bearcad.session_log"                 , "bearcad.session_log()"),
    ("bearcad.debug.session_writes"        , "bearcad.debug.session_writes()"),
    ("bearcad.set_body_shadow"             , "bearcad.set_body_shadow{ body, shadow }"),
    ("bearcad.set_construction"            , "bearcad.set_construction(element, construction)   -- handle, list, or { kind = \"line\" }"),
    ("bearcad.ui.set_dim"                     , "bearcad.ui.set_dim(axis, value)"),
    ("bearcad.ui.set_dim_label_offset"        , "bearcad.ui.set_dim_label_offset(axis, offset)"),
    ("bearcad.ui.set_gizmo"                   , "bearcad.ui.set_gizmo{ name, value }"),
    ("bearcad.set_joint_rest"              , "bearcad.set_joint_rest(op)"),
    ("bearcad.set_material"                , "bearcad.set_material{ body, material }"),
    ("bearcad.set_name"                    , "bearcad.set_name(element, name)"),
    ("bearcad.set_parameter"               , "bearcad.set_parameter(name, expression)"),
    ("bearcad.set_unit_parameter"          , "bearcad.set_unit_parameter{ instance, name, value, expression }"),
    ("bearcad.set_units"                   , "bearcad.set_units{ length, angle, component, sketch }"),
    ("bearcad.set_visible"                 , "bearcad.set_visible(element, visible)   -- handle, list, or { kind = \"plane\" }; boolean only"),
    ("bearcad.shell"                       , "bearcad.shell{ bodies, faces, thickness, name }"),
    ("bearcad.sketch_faces"                , "bearcad.sketch_faces(sketch?)   -- closed loops/circles/text/regions; pass one to extrude{ profiles = face }"),
    ("bearcad.sketch_conflicts"            , "bearcad.sketch_conflicts(sketch?)"),
    ("bearcad.sketch_dof"                  , "bearcad.sketch_dof(sketch?)"),
    ("bearcad.slice"                       , "bearcad.slice{ bodies, cutters, extend, name }"),
    ("bearcad.slice_sketch"                , "bearcad.slice_sketch{ sketch, lines, circles, faces, cutters }"),
    ("bearcad.sphere"                      , "bearcad.sphere{ radius, at?, name? }"),
    ("bearcad.debug.sqlite_scalar"         , "bearcad.debug.sqlite_scalar(sql)"),
    ("bearcad.status"                      , "bearcad.status()"),
    ("bearcad.sweep"                       , "bearcad.sweep{ profiles, circle, circles, polygon, path, bodies, body, name }"),
    ("bearcad.sync_unit"                   , "bearcad.sync_unit(value)"),
    ("bearcad.text"                        , "bearcad.text{ text, x, y, size, font, bold, italic, underline, rotation, wrap, flip, name }"),
    ("bearcad.debug.tool_row"              , "bearcad.debug.tool_row()"),
    ("bearcad.debug.tool_table"            , "bearcad.debug.tool_table()"),
    ("bearcad.ui.add_geometric_constraint" , "bearcad.ui.add_geometric_constraint(name)"),
    ("bearcad.ui.ai_mcp"                   , "bearcad.ui.ai_mcp(how)"),
    ("bearcad.ui.apply_construction"       , "bearcad.ui.apply_construction(construction)"),
    ("bearcad.ui.apply_visibility"         , "bearcad.ui.apply_visibility(visible)"),
    ("bearcad.ui.ai_pane_sections"         , "bearcad.ui.ai_pane_sections()"),
    ("bearcad.ui.ai_sections"              , "bearcad.ui.ai_sections(how)"),
    ("bearcad.ui.angle_snap"               , "bearcad.ui.angle_snap(degrees)"),
    ("bearcad.ui.animate_joints"           , "bearcad.ui.animate_joints(on?)"),
    ("bearcad.ui.animate_zoom_to_fit"      , "bearcad.ui.animate_zoom_to_fit(on?)"),
    ("bearcad.ui.auto_zoom"                , "bearcad.ui.auto_zoom(on?)"),
    ("bearcad.ui.camera"                   , "bearcad.ui.camera{ yaw, pitch, distance, target, projection, shading, ground }?   -- no fields = read"),
    ("bearcad.ui.changelog"                , "bearcad.ui.changelog(verb?)"),
    ("bearcad.ui.click"                    , "bearcad.ui.click(x, y, { shift?, ctrl?, cmd? }?)"),
    ("bearcad.ui.click_ground"             , "bearcad.ui.click_ground(x, y, { shift?, ctrl?, cmd? }?)"),
    ("bearcad.ui.click_world"              , "bearcad.ui.click_world(x, y, z, { shift?, ctrl?, cmd? }?)"),
    ("bearcad.ui.double_click"             , "bearcad.ui.double_click(x, y)"),
    ("bearcad.ui.repeat_tool"              , "bearcad.ui.repeat_tool{ axis?, count?, gap?, distance?, offset?, to_end?, computed?, around?, flip? }"),
    ("bearcad.ui.close_tab"                , "bearcad.ui.close_tab(index?)"),
    ("bearcad.ui.complete_all_tutorials"   , "bearcad.ui.complete_all_tutorials()"),
    ("bearcad.ui.complete_tutorial"        , "bearcad.ui.complete_tutorial(name)"),
    ("bearcad.ui.context_menu"             , "bearcad.ui.context_menu()"),
    ("bearcad.ui.detach_tab"               , "bearcad.ui.detach_tab(index?)"),
    ("bearcad.ui.drag"                     , "bearcad.ui.drag(x0, y0, x1, y1)"),
    ("bearcad.ui.drag_ground"              , "bearcad.ui.drag_ground(x0, y0, x1, y1)"),
    ("bearcad.ui.drag_world"               , "bearcad.ui.drag_world(x0, y0, z0, x1, y1, z1)"),
    ("bearcad.ui.elements_graph"           , "bearcad.ui.elements_graph{ shadow_bodies? }"),
    ("bearcad.ui.elements_view"            , "bearcad.ui.elements_view(name)"),
    ("bearcad.ui.focus_calibrate"          , "bearcad.ui.focus_calibrate()"),
    ("bearcad.ui.focus_dim"                , "bearcad.ui.focus_dim(axis)"),
    ("bearcad.ui.focus_name"               , "bearcad.ui.focus_name()"),
    ("bearcad.ui.focused_window"           , "bearcad.ui.focused_window()"),
    ("bearcad.ui.first_person"             , "bearcad.ui.first_person(on?)"),
    ("bearcad.ui.first_person_advance"     , "bearcad.ui.first_person_advance(seconds)"),
    ("bearcad.ui.first_person_fly"         , "bearcad.ui.first_person_fly(on?)"),
    ("bearcad.ui.first_person_jump"        , "bearcad.ui.first_person_jump()"),
    ("bearcad.ui.first_person_look"        , "bearcad.ui.first_person_look(dx, dy)"),
    ("bearcad.ui.first_person_move"        , "bearcad.ui.first_person_move{ forward, strafe }"),
    ("bearcad.ui.first_person_scale"       , "bearcad.ui.first_person_scale(scale)"),
    ("bearcad.ui.ground"                   , "bearcad.ui.ground(name)"),
    ("bearcad.ui.help"                     , "bearcad.ui.help(on?)"),
    ("bearcad.ui.install_age"              , "bearcad.ui.install_age(days?)"),
    ("bearcad.ui.key"                      , "bearcad.ui.key(name, { shift?, ctrl?, cmd? }?)"),
    ("bearcad.ui.keydown"                  , "bearcad.ui.keydown(name, { shift?, ctrl?, cmd? }?)"),
    ("bearcad.ui.keyup"                    , "bearcad.ui.keyup(name, { shift?, ctrl?, cmd? }?)"),
    ("bearcad.ui.mcmaster"                 , "bearcad.ui.mcmaster(verb?, part?)"),
    ("bearcad.ui.menu_structure"           , "bearcad.ui.menu_structure()"),
    ("bearcad.ui.move"                     , "bearcad.ui.move(x, y)"),
    ("bearcad.ui.move_ground"              , "bearcad.ui.move_ground(x, y)"),
    ("bearcad.ui.move_world"               , "bearcad.ui.move_world(x, y, z)"),
    ("bearcad.ui.new_tab"                  , "bearcad.ui.new_tab{ same }?"),
    ("bearcad.ui.orbit"                    , "bearcad.ui.orbit(dx, dy)"),
    ("bearcad.ui.os_open"                  , "bearcad.ui.os_open(path)"),
    ("bearcad.ui.palette"                  , "bearcad.ui.palette(query, argument?)   -- or palette{ open = true|false }"),
    ("bearcad.ui.pan"                      , "bearcad.ui.pan(dx, dy)"),
    ("bearcad.ui.pane"                     , "bearcad.ui.pane(pane, visible)"),
    ("bearcad.ui.pane_rect"                , "bearcad.ui.pane_rect(pane)"),
    ("bearcad.ui.drawing_view_rect"        , "bearcad.ui.drawing_view_rect(view)"),
    ("bearcad.ui.drawing_loupe_rect"       , "bearcad.ui.drawing_loupe_rect{ view, index, magnified? }   -- { x, y, w, h, band, handle } — the circle's box in window coords, the px of rim that resizes it, and the centre dot that moves it"),
    ("bearcad.ui.elements_row_rect"        , "bearcad.ui.elements_row_rect(label)"),
    ("bearcad.ui.context_row_rect"         , "bearcad.ui.context_row_rect(label)"),
    ("bearcad.ui.menu_items"               , "bearcad.ui.menu_items()   -- labels of the open context menu's items, in order"),
    ("bearcad.ui.menu_item_rect"           , "bearcad.ui.menu_item_rect(label)   -- { x, y, w, h } of that item, window coords"),
    ("bearcad.ui.pane_scroll"              , "bearcad.ui.pane_scroll(pane)"),
    ("bearcad.ui.picker_focus"             , "bearcad.ui.picker_focus(name)"),
    ("bearcad.ui.reorder_tab"              , "bearcad.ui.reorder_tab(from, to)"),
    ("bearcad.ui.report_issue"             , "bearcad.ui.report_issue(verb?)"),
    ("bearcad.ui.right_click"              , "bearcad.ui.right_click(x, y, { shift?, ctrl?, cmd? }?)"),
    ("bearcad.ui.right_click_ground"       , "bearcad.ui.right_click_ground(x, y, { shift?, ctrl?, cmd? }?)"),
    ("bearcad.ui.right_drag"               , "bearcad.ui.right_drag(dx, dy)"),
    ("bearcad.ui.right_drag_pan"           , "bearcad.ui.right_drag_pan(dx, dy)"),
    ("bearcad.ui.screenshot"               , "bearcad.ui.screenshot(path?, region?)"),
    ("bearcad.ui.scroll_pane"              , "bearcad.ui.scroll_pane(pane, dy)"),
    ("bearcad.ui.set_home_view"            , "bearcad.ui.set_home_view()"),
    ("bearcad.ui.settings"                 , "bearcad.ui.settings(verb?)"),
    ("bearcad.ui.shading"                  , "bearcad.ui.shading(name)   -- wireframe, transparent, solid, solid_wireframe, realistic, loose_pencil, dark_pencil, color_pencil, watercolor"),
    ("bearcad.ui.snapping"                 , "bearcad.ui.snapping(on?)"),
    ("bearcad.ui.tab"                      , "bearcad.ui.tab(index?)"),
    ("bearcad.ui.tab_count"                , "bearcad.ui.tab_count()"),
    ("bearcad.ui.tabs"                     , "bearcad.ui.tabs()"),
    ("bearcad.ui.toggle_construction"      , "bearcad.ui.toggle_construction()"),
    ("bearcad.ui.toggle_projection"        , "bearcad.ui.toggle_projection()"),
    ("bearcad.ui.toggle_visibility"        , "bearcad.ui.toggle_visibility()"),
    ("bearcad.ui.tool"                     , "bearcad.ui.tool(name?) -- no name reads the armed tool"),
    ("bearcad.ui.tool_hints"               , "bearcad.ui.tool_hints(on?)"),
    ("bearcad.ui.tool_mode"                , "bearcad.ui.tool_mode(mode?)"),
    ("bearcad.ui.toolbar_shortcuts"        , "bearcad.ui.toolbar_shortcuts()"),
    ("bearcad.ui.toolbar_tools"            , "bearcad.ui.toolbar_tools()"),
    ("bearcad.ui.touch"                    , "bearcad.ui.touch(on?)"),
    ("bearcad.ui.tutorial"                 , "bearcad.ui.tutorial(name)"),
    ("bearcad.ui.tutorial_assist"          , "bearcad.ui.tutorial_assist()"),
    ("bearcad.ui.tutorial_bubble"          , "bearcad.ui.tutorial_bubble()"),
    ("bearcad.ui.tutorial_end"             , "bearcad.ui.tutorial_end()"),
    ("bearcad.ui.tutorial_highlight"       , "bearcad.ui.tutorial_highlight()"),
    ("bearcad.ui.tutorial_narration"       , "bearcad.ui.tutorial_narration()"),
    ("bearcad.ui.tutorial_next"            , "bearcad.ui.tutorial_next()"),
    ("bearcad.ui.tutorial_orb"             , "bearcad.ui.tutorial_orb()"),
    ("bearcad.ui.tutorial_pane"            , "bearcad.ui.tutorial_pane(verb?)"),
    ("bearcad.ui.tutorial_prompt"          , "bearcad.ui.tutorial_prompt(verb?, arg?)"),
    ("bearcad.ui.tutorial_step"            , "bearcad.ui.tutorial_step()"),
    ("bearcad.ui.tutorials"                , "bearcad.ui.tutorials()"),
    ("bearcad.ui.type"                     , "bearcad.ui.type(text)"),
    ("bearcad.ui.unstart_all_tutorials"    , "bearcad.ui.unstart_all_tutorials()"),
    ("bearcad.ui.update_channel"           , "bearcad.ui.update_channel(channel?)"),
    ("bearcad.ui.view"                     , "bearcad.ui.view(…)"),
    ("bearcad.ui.view_home"                , "bearcad.ui.view_home()"),
    ("bearcad.ui.viewport"                 , "bearcad.ui.viewport() -- { width, height, x, y }"),
    ("bearcad.ui.wait"                     , "bearcad.ui.wait(frames)"),
    ("bearcad.ui.wait_ms"                  , "bearcad.ui.wait_ms(ms)"),
    ("bearcad.ui.wheel"                    , "bearcad.ui.wheel(scroll)"),
    ("bearcad.ui.headless"                 , "bearcad.ui.headless()   -- true when the run has no OS window"),
    ("bearcad.debug.widget_id_warnings"    , "bearcad.debug.widget_id_warnings()"),
    ("bearcad.ui.window_count"             , "bearcad.ui.window_count()"),
    ("bearcad.ui.windows"                  , "bearcad.ui.windows()"),
    ("bearcad.ui.workbench"                , "bearcad.ui.workbench(name)"),
    ("bearcad.ui.zoom_fit"                 , "bearcad.ui.zoom_fit()"),
    ("bearcad.undo"                        , "bearcad.undo()"),
    ("bearcad.unit_link"                   , "bearcad.unit_link(unit, mode)"),
    ("bearcad.version"                     , "bearcad.version()"),
    ("bearcad.visible"                     , "bearcad.visible(element)   -- effective visibility, component chain included"),
];
